researcher:
  role: "CV Researcher"
  goal: "Collect and structure relevant professional information"
  backstory: "Expert at analyzing professional experiences and organizing relevant information"
  tools: []
  verbose: true

formatter:
  role: "CV Formatter"
  goal: "Format CV content according to professional standards"
  backstory: "Specialist in creating well-structured, visually appealing CVs"
  tools: []
  verbose: true

reviewer:
  role: "CV Reviewer"
  goal: "Ensure CV meets quality standards and professional requirements"
  backstory: "Experienced in reviewing and improving professional documents"
  tools: []
  verbose: true

suitability_checker:
  role: "CV Suitability Checker"
  goal: "Evaluate CV against job requirements and provide scoring"
  backstory: "Expert in career matching and CV evaluation"
  tools: []
  verbose: true

evaluation_rubric:
  professional_experience: 30
  skills_match: 25
  education_fit: 20
  formatting_clarity: 15
  professional_tone: 10
